set(CMAKE_SYSTEM_NAME iOS)

if(NOT DEFINED CMAKE_OSX_ARCHITECTURES OR CMAKE_OSX_ARCHITECTURES STREQUAL "")
    if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
        set(CMAKE_OSX_ARCHITECTURES arm64)
    else()
        set(CMAKE_OSX_ARCHITECTURES x86_64)
    endif()
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0)
set(CMAKE_OSX_SYSROOT iphonesimulator)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH YES)

set(OPENSSL_PATCH ${CMAKE_CURRENT_LIST_DIR}/../../patch/ios_sim.patch)
list(APPEND OPENSSL_CONFIGURE_OPTIONS -mios-simulator-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET})
foreach(arch IN LISTS CMAKE_OSX_ARCHITECTURES)
    list(APPEND OPENSSL_CONFIGURE_OPTIONS "-arch ${arch}")
endforeach()
list(APPEND OPENSSL_CONFIGURE_OPTIONS
    -fno-common
    no-asm
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
